### ISSUE TITLE
Renderização de livro a partir de link de doc

### ISSUE THREAD

**Issue by Dovyski** [practice-uffs/maker#14]
O objetivo dessa issue é implementar o fluxo para buscar o conteúdo de um arquivo no google drive e, a partir dele, gerar um livro em formato PDF. A seguir estão os passos para que essa issue seja completada.

- [x] Criar uma página `Livro`

Criar uma página nova (no menu superior ela se chamada `Livro`, nas views é `resources/views/book.blade.php`,  e no controller é `App/Http/Controller/BookController.php`, rota `/livro`). Essa página deve conter um campo (input) e um botão para enviar. O usuário informará o link de um documento do google drive nesse input.

- [x] Buscar o conteúdo do documento

Utilizando a informação do campo input, buscar o conteúdo do documento e salvar esse conteúdo como texto puro (sem formatação alguma) localmente. É importante que o conteúdo seja salvo em uma pasta própria, porque teremos outros elementos dentro dessa pasta (que são usados pela ferramenta de criação do livro).

- [x] Gerar o livro PDF

Utilizar o [Ibis](https://github.com/themsaid/ibis) para gerar um livro em PDF a partir do conteúdo baixado. Você terá que inicializar a pasta (onde está o texto puro) com os arquivos do ibis via linha de comando. Dá uma olhada no projeto [id-uffs-avatar](https://github.com/ccuffs/id-uffs-avatar) para ver como um arquivo de linha de comando é executado em integração com o projeto. Para o teu caso, você pode assumir que o comando `ibis` está disponível para rodar (não precisa instalar ele), então é uma questão de rodar algo na linha de comando a partir do Laravel e imprimir na tela a saída desse comando (olha [esse arquivo](https://github.com/ccuffs/id-uffs-avatar/blob/master/app/Cli/SciScraper.php) por exemplo).

**Comment by GuilhermeGraeff** [comment]
Eu vou esperar os PR's que estão ativos entrarem pra poder deixar as coisas que eu atualizei de acordo com o que está nos PR's

Por exemplo nas rotas do web.php, e nos controllers.
