### ISSUE TITLE
Geração do livro como um job (queue)

### ISSUE THREAD

**Issue by CleissonVieira** [practice-uffs/maker#24]
Utilizar a queue do laravel na geração do livro.
Como a geração do livro demora alguns segundos, para permitir que o usuário navegue livremente pelo site, deve-se usar as queues/Job .
Dessa maneira também é registrado no banco os jobs que foram criados e também os que falharam.

**Comment by GuilhermeGraeff** [comment]
No dia da reunião eu comecei o desenvolvimento desta tarefa, acabei me esquecendo de mudar de 'to do' para 'in progress', estou alterando agora daí
