### ISSUE TITLE
Opção de atualizar livro após ser gerado

### ISSUE THREAD

**Issue by CleissonVieira** [practice-uffs/maker#27]
Hoje um livro didático é gerado pelo maker através de um arquivo no google drive. Porém quando esse arquivo é atualizado com novas informações é necessário gerar um novo livro para obtê-las.

**Objetivo** é criar uma opção dentro do livro, ou na listagem do mesmo, para atualizar os dados de acordo com o momento atual do arquivo no drive.

**Comment by GuilhermeGraeff** [comment]
No desenvolvimento da tarefa #24 eu creio que eu já implementei esta feature.

Logo Logo eu vou conseguir fazer o PR da minha tarefa, daí a gente pode verificar isso com mais detalhes.

**Comment by CleissonVieira** [comment]
Perfeito Gui, estou finalizando essa tarefa, verifiquei seu PR e nele você informa sobre essa feature.
Perfeitoo!!
