### ISSUE TITLE
Ajustes para lançamento

### ISSUE THREAD

**Issue by CleissonVieira** [practice-uffs/maker#30]
### Geral:
- [x] Atualizar layout para diferenciar do Mural, dar uma cara própria do maker, utilizando uma ;
- [Aqui](https://drive.google.com/drive/u/0/folders/1ymOvitNBOkBeU2RStVchrD6Rg8Ar4FB-) existem [identidades visuais do PRACTICE](https://drive.google.com/drive/u/0/folders/1ymOvitNBOkBeU2RStVchrD6Rg8Ar4FB-) que podem ser utilizadas

### Atualizar dados da página inicial antes de logar:
- [x] Alterar nome " Laravel" ao lado da logo do PRACTICE para Maker
- [x] Criar um breve resumo do Livro didático digital e do LBK
- [x] Remover conteúdo que tem dados aleatórios e não estão sendo utilizados

### Atualizar dados da tela de login
- [x] Alterar nome " Laravel" ao lado da logo do PRACTICE para Maker
- [x] Melhorar botão de entrar, é necessário clicar duas vezes em entrar para acessar

### Atualizar e melhorar tela inicial após entrar com usuário e senha:
- [x] Remover dados que não estão sendo utilizados no template.
- [x] Atualizar todos os dados para dados reais e úteis

## Acessando "Ferramentas": 
- [x] Arrumar rotas para Livro digital no maker, está incorreto, se utilizar "/livro/index" direciona sem erro.
- [x] Atualizar a descrição do Livro digital e Poster
- [x] Remover a ferramenta Neptune 
- [x] Erro ao gerar um site, o mesmo é gerado, porém ao acessar da erro no php (não está criando o arquivo index para o site);

## Relacionadas ao acesso ao google drive:
- [x] Retirar funções que não estão sendo utilizadas do service/GoogleDoc.php.
- [x] Retirar views que eram utilizadas pelas funções do GoogleDoc.php que não estão sendo utilizadas.

**Comment by GuilhermeGraeff** [comment]
Bom dia!!

Estou desenvolvendo, não consegui identificar este ajuste aqui, "Melhorar botão de entrar, é necessário clicar duas vezes em entrar para acessar".

<hr />

![image](https://user-images.githubusercontent.com/48657331/132006677-3df9edee-a7f0-408d-b219-0413381c5ba6.png)

<hr />

![image](https://user-images.githubusercontent.com/48657331/132006695-7893e9df-daa2-4af7-b026-44265e8f1734.png)
 
<hr />

Seria porque o primeiro botão redireciona e o segundo conecta?
Daí a ideia seria reduzir estes dois cliques para apenas um?
@CleissonVieira

**Comment by CleissonVieira** [comment]
O problema está nesta tela.

![image](https://user-images.githubusercontent.com/29258164/132438875-451d62ed-7539-4e4f-ba75-b327c65ce618.png)

Inserindo meu login e senha clico no botão de "Entrar"  e sou direcionado para mesma tela, clico em entrar novamente, e na segunda tentativa acesso meu usuário.
