### ISSUE TITLE
Atualizar Readme para rodar o Livro digital localmente

### ISSUE THREAD

**Issue by CleissonVieira** [practice-uffs/maker#33]
Com o readme atual eu consigo instalar todas as dependências, iniciar o maker localmente e utilizar o LBK.
Porém o Livro Didático Digital não é possível. 
Em conversa com @GuilhermeGraeff fui informado que existem alguns passos a seguir para utilizar localmente para teste.

**Objetivo:** Atualizar o readme com os passos e recursos necessários para testar o livro didático digital

**Comment by GuilhermeGraeff** [comment]
O Cleisson teve alguns problemas ao usar o composer para instalar o Ibis, terei que atualizar o readme.

Vou reabrir esta issue e criar um novo Pull Request na mesma branch para isso.

**Comment by CleissonVieira** [comment]
Em conversa com Guilherme ele informou que diante dos problemas no sistema operacional debian o mesmo vai verificar e rodar no linux o livro didático para identificar e resolver os problemas
