### ISSUE TITLE
Manual sobre Markdown

### ISSUE THREAD

**Issue by CleissonVieira** [practice-uffs/maker#37]
Criar um manual mostrando as tags markdown, para que serve e exemplos.

[Pasta com manual.](https://drive.google.com/drive/u/0/folders/1iaOCcvXS5nfS9Pz0ktcUZT-7HOTAdCFc)

**Comment by CleissonVieira** [comment]
Esse manual será disponibilizado nas plataformas onde serão utilizados e no site em forma de cartilha.

**Comment by CleissonVieira** [comment]
@Claudineia-VR Por gentileza.
Preciso de uma revisão, padronização e adaptação desse manual para cartilha.
Aguardo retorno para dar sequência

**Comment by CleissonVieira** [comment]
@GuilhermeGraeff Como desenvolvedor do livro didático digital.
Por gentileza, analise esse manual e informa se precisa de informações a mais para os usuários que forem utilizar do sistema.
Conforme achar necessários vamos moldando melhor o manual.

**Comment by Claudineia-VR** [comment]
> @Claudineia-VR Por gentileza.
> Preciso de uma revisão, padronização e adaptação desse manual para cartilha.
> Aguardo retorno para dar sequência

@practice-uffs/con-conteudo 
@mariagelain

**Comment by GuilhermeGraeff** [comment]
@CleissonVieira 
Algumas observações sobre a cartilha, ainda estou analisando o ibis pra entender melhor como ele funciona, vou ir atualizando aqui :).

Na sua maioria o [Ibis](https://github.com/themsaid/ibis) utiliza o markdown comum, daí a maior parte do que está presente neste docs faz sentido e funciona.

Porém, como é um livro, algumas informações a mais nos títulos são importantes, por exemplo: 
![image](https://user-images.githubusercontent.com/48657331/132710847-3e5fe603-292a-43a7-93e4-3f6145e3da8c.png)



E como o ibis utiliza diferentes arquivos markdown para fazer a separação dos capítulos(quebra de página) e nós temos apenas um docs, o primeiro título e os seguintes perdem a simplicidade para utilização, tendo que usar uma \<div\> html para fazer a quebra de página (não sei se isso é o ideal).



<hr>

### Na parte das citações, o ibis trabalha de uma maneira um pouco diferente.

- Para citações normais: >{quote} Citação vai aqui.
![image](https://user-images.githubusercontent.com/48657331/132712578-89eec2e7-a323-47ac-8b3c-5ff3cf46e238.png)

- Para notas: >{notice} Note vai aqui.
![image](https://user-images.githubusercontent.com/48657331/132712168-5e890986-20a0-46f8-abdd-662528b08cc8.png)

- Para avisos: >{warning} Aviso vai aqui.
![image](https://user-images.githubusercontent.com/48657331/132713190-84027cf2-b06f-4e7c-912a-426054811475.png)

**Comment by CleissonVieira** [comment]
Perfeito @GuilhermeGraeff, fiz todas as correções que sugeriu
Caso seja necessário, pode comentar novas alterações que eu ajusto. 
Muito obrigado!

**Comment by GuilhermeGraeff** [comment]
Como foi retomado o assunto do Maker na reunião de líderes, eu rodei o maker localmente e notei que as alterações feitas na issue #49 sobre como os capítulos eram organizados não foram refletidas neste manual, vou fazer isso agora :+1:

**Comment by alissonpeloso** [comment]
@GuilhermeGraeff, a gente tem esse doc completinho? Acredito que dê pra fazer uma versão criada pelo próprio maker. No caso, gerar um markdown como manual e gerar o pdf através do maker. Também seria interessante criar uma issue pra adicionar esse manual no maker ou talvez um manual mais iterativo, como por exemplo, o da página inicial do Forms:

![image](https://user-images.githubusercontent.com/51202705/166479000-134fefe9-70d4-4ddd-98a2-2a8b7b3eb689.png)

**Comment by GuilhermeGraeff** [comment]
@alissonpeloso
Ótima ideia, vou dar uma olhada no manual para ver se está faltando alguma coisa e depois disso eu abro a issue referente a transformar isso em um PDF usando o maker, e também outra para colocar a explicação no próprio maker.

**Comment by GuilhermeGraeff** [comment]
Na issue #82 foi gerado um modelo em que foi aplicado as funcionalidades descritas neste manual.

Acredito que o próximo passo seria deixar estas funcionalidades para que o usuário consiga ver no maker.

**Comment by GuilhermeGraeff** [comment]
Retirei essa parte do manual, pois testei e n funcionou, mas no mais o desenvolvimento das coisas relacionadas a isso seguem na issue #85 
```Alinhamentos:
A esquerda: usar : do lado esquerdo.
Exemplo :esquerdo
A direita: usar : do lado direito.
Exemplo direito:
Centralizado: usar : dos dois lados.
Exemplo :centralizado:	```
