### ISSUE TITLE
Geração inicial de sites

### ISSUE THREAD

**Issue by Dovyski** [practice-uffs/maker#38]
O objetivo dessa tarefa é criar o aparato inicial para que páginas web sejam geradas a partir do maker. A ideia básica é o seguinte:

- Usuário informa um link do google docs para ser usado como conteúdo (cada seção com título formatado como `Title` será considerado uma página/url).
- Maker lê o conteúdo do google docs e cria um arquivo html para cada seção do docs (o conteúdo do arquivo é o conteúdo daquela seção no docs).

Nesse primeiro momento, o layout de cada arquivo html não é importante (vamos melhorar isso no futuro).

Eu acho que a melhor forma de organizar isso tudo é criado um job Laravel que faça o que foi descrito acima. O job deve utilizar uma configuração do Laravel (pode ser o arquivo `config/sites.php`) que informe a pasta no sistema onde os arquivos serão colocados. Cada site deve ser colocado em uma pasta cujo nome é o id do próprio site.

Por exemplo, se o job receber via config que a paste de site é `D:\sites` e que ele está gerando o site de id `20`, os arquivos desse site serão colocados todos na pasta `D:\sites\20` (se a pasta `20` não existir, ela precisa ser criada pelo job).

**Comment by GuilhermeGraeff** [comment]
Eu comecei o desenvolvimento desta tarefa quarta-feira (15/09), porém não me atentei em mudar para 'in progress'.
Estou mudando agora.
