### ISSUE TITLE
Organizar treinamento para trabalhos no servidor/Google Console

### ISSUE THREAD

**Issue by Dovyski** [practice-uffs/maker#50]
Para colocar o maker no ar, precisamos ter um conhecimento mínimo da gerência do projeto em produção. O objetivo dessa issue é agendar e conduzir um treinamento sobre o assunto. Seria muito interessante gravar essa reunião.

Gravar treinamento e disponibilizar em [nossa pasta do drive](https://drive.google.com/drive/u/0/folders/1AxDA7xDbmomoA_i_SIUn_UYksbfZYuvf)

**Comment by GuilhermeGraeff** [comment]
Eu fiz um [doodle](https://doodle.com/poll/t74yazpdve6ea5fa?utm_source=poll&utm_medium=link) para poder marcar o treinamento com o Fernando sobre gerência do projeto em produção.

Vai ficar gravada este treinamento, e os devs que quiserem participar fiquem a vontade :).

@practice-uffs/dev

**Comment by GuilhermeGraeff** [comment]
Foi definido em reunião que por conta da geração de conteúdo o Maker precisa de mais um tempo no forno até o lançamento, daí essa reunião será adiada.

Retornaremos o assunto em futuras reuniões semanais.
