### ISSUE TITLE
Colocar a parte da geração do livro digital no ar

### ISSUE THREAD

**Issue by GuilhermeGraeff** [practice-uffs/maker#57]
Foi levantado nas duas reuniões de líder que eu participei que a funcionalidade da geração de livros digitáis deveria ser utilizável.

Pelo menos para testes, isso envolve alguns ajustes no que está na dev agora, como a parte do credentials e do token.

**Comment by alissonpeloso** [comment]
Aguardando informação sobre servidor para sabermos como colocar o maker em produção.

**Comment by GuilhermeGraeff** [comment]
Acho que esta aqui está em andamento né? Pelo menos a versão de testes. @alissonpeloso

**Comment by alissonpeloso** [comment]
yep
