### ISSUE TITLE
Imagens no ibis não são renderizadas a partir do link 

### ISSUE THREAD

**Issue by GuilhermeGraeff** [practice-uffs/maker#63]
Na issue [1068](https://github.com/practice-uffs/programa/issues/1068) do programa, desenvolvendo o livro digital para um conteúdo específico, notei que o Ibis não conseguiu renderizar uma imagem a partir de um link.

O intuito desta issue é verificar o motivo desse bug acontecer e tentar arrumar.

Na issue foi dada a volta por cima utilizando a imagem em base:64 (muuuuito inviável).

**Comment by Dovyski** [comment]
A ideia de usar base:64 não é tão inviável. O que o maker pode fazer é procurar por urls de imagens no texto do drive e, antes de enviar para o ibis, gerar o base:64 do arquivo baixado pela url. Algo como

```php
$url = 'https://url/imagem/encontrada/no/texto.png';
$content = file_get_contents($url);
$base64 = base64_encode($content);
```

**Comment by GuilhermeGraeff** [comment]
Certoo, não tinha pensado nesta possibilidade, valeu pela dica!!

Embora tenha levado mais ou menos uns 18 segundos para gerar o PDF em minha máquina, como utilizamos os Jobs do Laravel, acredito que funcione tranquilamente, o fluxo de geração de livros digitais não será tão grande também para ocorrerem conflitos, e mesmo se fossem solicitadas duas gerações de livros digitais acredito que tais conflitos não ocorreriam.

Como eu já estou envolvido com o fluxo de geração de livros digitais, vou pegar essa issue também :D.

**Comment by GuilhermeGraeff** [comment]
Agora eu fiquei um pouco na dúvida, primeiro, eu me equivoquei, os links diretos para o arquivo da imagem funcionam. 

Porém não sei se é assim que deveria ser, pois para hospedar uma imagem e gerar o link direto pro arquivo me parece um pouco complicado para alguém que seria um pouco mais leiga/o

**Comment by alissonpeloso** [comment]
@GuilhermeGraeff, lembra de atribuir uma sprint pra issue

**Comment by GuilhermeGraeff** [comment]
Ficou decidido que vamos pegar o id da imagem compartilhada:
```
https://drive.google.com/file/d/1MOPLcPPqLdWmYgw59pzFxbdEkw0975AN/view?usp=sharing
```

E subtituir neste link https://drive.google.com/uc?export=view&id=1MOPLcPPqLdWmYgw59pzFxbdEkw0975AN e daí sim colocar no Mark Down do Ibis:

```
![Titulo da imagem.](https://drive.google.com/uc?export=view&id=1MOPLcPPqLdWmYgw59pzFxbdEkw0975AN)
```

**Comment by GuilhermeGraeff** [comment]
Pronto, agora se este pull request for aceito a issue [1068](https://github.com/practice-uffs/programa/issues/1068) pode seguir em frente, ainda mais depois que a issue #65 foi concluída, deixou o livro muito mais bonito. :smile:
