### ISSUE TITLE
Dar a oportunidade de gerar um livro na versão dark

### ISSUE THREAD

**Issue by GuilhermeGraeff** [practice-uffs/maker#68]
O [Ibis](https://github.com/themsaid/ibis) tem a opção de tema claro e escuro, disponibilizar esta opção para o usuário.

Atualmente só podemos gerar a versão 'light' do livro digital, o @alissonpeloso sugeriu gerar a opção dark também, eu acredito que esta não é uma tarefa tão difícil, tendo em vista que seria apenas alterar o chamado do ibis e algumas coisas no asset do ibis também.

**Comment by GuilhermeGraeff** [comment]
Vou aguardar as atualizações no visual do maker na issue #74 do @CleissonVieira  para poder implementar o botão de gerar o livro light ou dark

**Comment by CleissonVieira** [comment]
Perfeito, criei uma nova tarefa #75 para dar continuidade
Realizei Pull request da tarefa #74 para você dar continuidade nessa issue

**Comment by GuilhermeGraeff** [comment]
Feeito, valeeeu, isso me ajuda bastante ;)
