### ISSUE TITLE
Listagem de arquivos compartilhados em conta Google

### ISSUE THREAD

**Issue by Dovyski** [practice-uffs/maker#7]
O objetivo dessa tarefa é incrementar a classe `App\Services\GoogleDocs` para que ela tenha um método que liste os arquivos compartilhados com a conta do Google do Practice.

Atualmente a obtenção de documentos do Google Drive está sendo feita na conta do Guilherme. Ela tem que ser feita pela conta do Google do Practice.

**Comment by GuilhermeGraeff** [comment]
Eu acredito que esta issue poderia ser fechada por enquanto e poderíamos voltar a ela quando o projeto estivesse mais encaminhado.

Estudando mais a fundo as permissões que o token/credentials oferecem, creio que não seria bom utilizar o drive do PRACTICE, já que ele é utilizado para gerência de outras atividades e tudo, e prezamos para que estes dados estejam seguros.

Uma alternativa que eu testei foi criar um novo e-mail (mais um dentre tantos) practiceuffs.ebook@gmail.com e fazer o gerenciamento dos ebooks no drive deste e-mail. 

Mas isso geraria mais um e-mail e mais uma coisa para se preocupar, daí não sei como prosseguir.

**Comment by CleissonVieira** [comment]
Em reunião foi conversado para utilizar deste e-mail, citado no comentário acima, como oficial no momento para as credenciais do livro didático digital. Estou documentando no guia de Dev que está sendo feito.
Então tarefa vai ser continuada, e assim que concluída @GuilhermeGraeff vai informar nesta issue

**Comment by GuilhermeGraeff** [comment]
Como eu também tinha que usar e-mail para um drive na criação de Sites, eu decidi criar um novo e-mail practiceuffs.maker@gmail.com, então será com esse e-mail que será compartilhado tanto os e-books quanto os sites.

É com esse e-mail que será gerado o Token de autenticação do Drive.

Assim que o pull request da issue #29 entrar, eu vou criar uma branch e ajustar os nomes dos e-mails com que os serviços devem ser compartilhados.

Eu vou passar a informação do e-mail e da senha para o @CleissonVieira, para que fique tudo documentado.

**Comment by CleissonVieira** [comment]
Guilherme, aguardo via telegram os dados de senha do e-mail para documentar
Os Pull Requests já foram aceitos.
