### ISSUE TITLE
Adicionar um scroll na pré-visualização do conteúdo antes de gerar o pdf

### ISSUE THREAD

**Issue by GuilhermeGraeff** [practice-uffs/maker#70]
O @alissonpeloso sugeriu adicionar um scroll na pré-visualização do conteúdo antes de gerar o pdf, pois se não tem que rolar a página até embaixo pra gerar o livro digital.

**Comment by CleissonVieira** [comment]
Na issue #74 está sendo implementada essa tarefa, finalizando aqui.
