### ISSUE TITLE
Gerar a diagramação do Manual em markdown

### ISSUE THREAD

**Issue by GuilhermeGraeff** [practice-uffs/maker#82]
Proveniente do comentário da isse: #37

**Comment by GuilhermeGraeff** [comment]
[Pasta com o tutorial](https://drive.google.com/drive/u/1/folders/1OW0cm37gQZLf0we5LTQ6UDmrs8lMQ7T_)

@alissonpeloso dá uma olhada e um feedback aqui :)

**Comment by alissonpeloso** [comment]
Por mim está ok, mandei para Eweline testar
